export enum TppItemType {
  TARGET_POPULATION = "TARGET_POPULATION",
  DESIRED_EFFICACY_PROFILE = "DESIRED_EFFICACY_PROFILE",
  DESIRED_IMMUNOLOGICAL_RESPONSE = "DESIRED_IMMUNOLOGICAL_RESPONSE",
  ADMINISTRATION_ROUTE = "ADMINISTRATION_ROUTE",
  STORAGE_CONDITION = "STORAGE_CONDITION",
  OTHER = "OTHER",
}

